Changes for PowerAPI monitoring

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -1,54 +1,73 @@
-name: Java CI
-
-on:
-  pull_request:
-    branches:
-    - master
-  push:
-    branches:
-    - master
-
 jobs:
   build:
     name: Test on java-version ${{ matrix.java-version }} and ${{ matrix.os }}
-    runs-on: ${{ matrix.os }}
+    runs-on: self-hosted
+    steps:
+    - continue-on-error: true
+      uses: actions/checkout@v3
+    - continue-on-error: true
+      if: matrix.os == 'ubuntu-latest'
+      name: Check limited Guava usage
+      run: "if grep --with-filename --line-number --no-messages --recursive --exclude-dir=.github\
+        \ \"com.google.common.base.Objects\" .; then\n  echo \"Error: use java.util.Objects\
+        \ instead of com.google.common.base.Objects\"\n  exit 1\nfi\n"
+    - continue-on-error: true
+      name: Setup java ${{ matrix.java-version }}
+      uses: actions/setup-java@v3
+      with:
+        distribution: temurin
+        java-version: ${{ matrix.java-version }}
+    - continue-on-error: true
+      name: Set environment variables
+      run: 'echo "DEV_VERSION=$(./gradlew properties | awk ''/^version:/ { print $2
+        }'')" >> $GITHUB_ENV
+
+        echo "RELEASE_VERSION=$(./gradlew properties -Prelease | awk ''/^version:/
+        { print $2 }'')" >> $GITHUB_ENV
+
+        '
+    - continue-on-error: true
+      if: matrix.os == 'ubuntu-latest'
+      name: Gradle build on Ununtu
+      run: './gradlew build
+
+        ./gradlew runFunctionalTest
+
+        javac -cp api/build/libs/minio-${DEV_VERSION}-all.jar functional/TestUserAgent.java
+
+        java -Dversion=${DEV_VERSION} -cp api/build/libs/minio-${DEV_VERSION}-all.jar:functional
+        TestUserAgent
+
+        ./gradlew clean
+
+        ./gradlew build -Prelease
+
+        javac -cp api/build/libs/minio-${RELEASE_VERSION}-all.jar functional/TestUserAgent.java
+
+        java -Dversion=${RELEASE_VERSION} -cp api/build/libs/minio-${RELEASE_VERSION}-all.jar:functional
+        TestUserAgent
+
+        '
+    - continue-on-error: true
+      if: matrix.os == 'windows-latest'
+      name: Gradle build on Windows
+      run: '$Env:Path += '';.''
+
+        gradlew.bat build
+
+        gradlew.bat runFunctionalTest
+
+        '
     strategy:
       matrix:
-        java-version: ['8', '11', '17']
-        os: [ubuntu-latest, windows-latest]
-
-    steps:
-      - uses: actions/checkout@v3
-      - name: Check limited Guava usage
-        if: matrix.os == 'ubuntu-latest'
-        run: |
-          if grep --with-filename --line-number --no-messages --recursive --exclude-dir=.github "com.google.common.base.Objects" .; then
-            echo "Error: use java.util.Objects instead of com.google.common.base.Objects"
-            exit 1
-          fi
-      - name: Setup java ${{ matrix.java-version }}
-        uses: actions/setup-java@v3
-        with:
-          distribution: temurin
-          java-version: ${{ matrix.java-version }}
-      - name: Set environment variables
-        run: |
-          echo "DEV_VERSION=$(./gradlew properties | awk '/^version:/ { print $2 }')" >> $GITHUB_ENV
-          echo "RELEASE_VERSION=$(./gradlew properties -Prelease | awk '/^version:/ { print $2 }')" >> $GITHUB_ENV
-      - name: Gradle build on Ununtu
-        if: matrix.os == 'ubuntu-latest'
-        run: |
-          ./gradlew build
-          ./gradlew runFunctionalTest
-          javac -cp api/build/libs/minio-${DEV_VERSION}-all.jar functional/TestUserAgent.java
-          java -Dversion=${DEV_VERSION} -cp api/build/libs/minio-${DEV_VERSION}-all.jar:functional TestUserAgent
-          ./gradlew clean
-          ./gradlew build -Prelease
-          javac -cp api/build/libs/minio-${RELEASE_VERSION}-all.jar functional/TestUserAgent.java
-          java -Dversion=${RELEASE_VERSION} -cp api/build/libs/minio-${RELEASE_VERSION}-all.jar:functional TestUserAgent
-      - name: Gradle build on Windows
-        if: matrix.os == 'windows-latest'
-        run: |
-          $Env:Path += ';.'
-          gradlew.bat build
-          gradlew.bat runFunctionalTest
+        java-version:
+        - '8'
+        - '11'
+        - '17'
+        os:
+        - ubuntu-latest
+        - windows-latest
+name: Java CI
+on:
+  repository_dispatch:
+    types: trigger-ga___gradle.yml
